---
title: "ITP-Shopify Store - Assignment 2 - Store Concept and Initial Shopify Setup"
author: "Leeann Lewis-Waddell"
date: today
format: 
  html: 
    toc: true
    toc-depth: 4
    number-sections: true
    code-link: true
    embed-resources: true
editor: visual
execute: 
  freeze: auto
---

# **Store Name & Concept**

## **Store Name: UGC University**

UGC University is a digital store front that caters to digital content creators in need of tools and systems to grow their platforms. Target audience includes not only new and seasoned content creators, but one-stop shopping for small business owners to amplify their brand reach. In addition to providing (physical & digital) systems to plan content, track income, expenses, and deal pipelines, UGC University is an ecosystem from which production equipment tailored for mobile content creation can be purchased in one place. Digital products will include guides and speaker events intended to inform and inspire new and established creators alike.

# **Target customer** 

The ideal customer is an entrepreneur interested in content creation for social media based advertising and brand building. This could be either a user generated content creator providing B2B services or a small business owner promoting their product or service. These people are creative pro-sumers who not only chronically online and spend a significant amount of time studying brand and ad strategy, but also see the value in investing in knowledge and tools to grow their reach and revenue. This demographic is subject to influence from the creator economy industry and will explore coaching opportunities based on the recommendation of their peers and the creators whose trajectory they admire.

# **Product category plan** 

Identify at least **three to five product categories** your store will include.

# **Initial Shopify setup evidence**

\
Include screenshots showing:

-   Your Shopify admin area

-   Your selected theme

-   Your homepage draft or theme customization page

# **Connection to CPP Farm Store** 

Write one paragraph explaining how your store concept or setup decisions could help you think about the CPP Farm Store consulting project.

# **Appendix**

-   [GitHub Repo](https://github.com/lewiswaddell/ITP-W04.git)

-   [GitHub Page](https://lewiswaddell.github.io/ITP-W04/)
